---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: 300 Clone required mediawiki version
      shell: "git clone --branch {{ mediawiki_version }} --depth 1 --single-branch https://github.com/wikimedia/mediawiki.git w/"
      args:
        chdir: "/home/dserver/mediawiki_root"
      become: "true"
      tags:
        - 300_clone_mediawiki

    - name: 300 Install core extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "/home/dserver/mediawiki_root/w/"
      become: "true"
      tags:
        - 300_clone_mediawiki

    - name: 300 Place composer install script
      template:
        src: ../../ansible_templates/install_composer.sh.j2
        dest: "/home/dserver/mediawiki_root/w/install_composer.sh"
        mode: 0777
      become: "true"
      tags:
        - 301_install_composer

    - name: 300 Install composer locally
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "cd $SYSTEM_ROOT_FOLDER_IN_CONTAINER/w && ./install_composer.sh"
      become: "true"
      tags:
        - 301_install_composer

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Run composer inside container
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "cd $SYSTEM_ROOT_FOLDER_IN_CONTAINER/w && php composer.phar install"
      become: "true"
      tags:
        - 302_run_composer

    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Place mediawiki install script
      template:
        src: ../../ansible_templates/install_mediawiki.sh.j2
        dest: "/home/dserver/mediawiki_root/w/install.sh"
        mode: 0777
      become: "true"
      tags:
        - 303_install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Install mediawiki inside container
      shell: "docker exec {{ mediawikiDockerServiceName }} bash -c 'cd $SYSTEM_ROOT_FOLDER_IN_CONTAINER/w && ./install.sh'"
      become: "true"
      tags:
        - 303_install_mediawiki
    
    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Place run_jobs_continuously.sh script
      template:
        src: ../../ansible_templates/run_jobs_continuously.sh.j2
        dest: "/home/dserver/mediawiki_root/w/run_jobs_continuously.sh"
        mode: 0777
      become: "true"
      tags:
        - 303_install_mediawiki

    - name: 300 Add settings to LocalSettings.php
      lineinfile:
        path: "/home/dserver/mediawiki_root/w/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - $wgArticlePath = '/wiki/$1';
        - $wgServer = "http://{{ mediawikiDomainNameInHostFile }}:8080";
        - $wgFileExtensions[] = 'pdf';
        - $wgMainCacheType = CACHE_NONE;
        - $wgRateLimits['edit']['anon'] = [ 1, 1 ];
        - $wgEnableUploads = true;
        - $wgShowExceptionDetails = true;
      become: "true"
      tags:
        - 304_adjust_localsettings

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Change admin user password
      shell: docker exec {{ mediawikiDockerServiceName }} bash
               -c "cd $SYSTEM_ROOT_FOLDER_IN_CONTAINER/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: "true"
      tags:
        - 304_adjust_localsettings

    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Set permissions on mediawiki root
      file:
        path: "/home/dserver/mediawiki_root/w/"
        owner: www-data
        recurse: yes
      become: "true"
      tags:
        - 304_adjust_localsettings

    - name: 300 execute_mediawiki_maintenance_runJobs
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "php w/maintenance/runJobs.php"
      become: "true"
      tags:
        - 304_adjust_localsettings

    - name: 300 place INITIAL_INSTRUCTIONS
      template:
        src: ../../ansible_templates/INITIAL_INSTRUCTIONS.j2
        dest: "/home/dserver/INITIAL_INSTRUCTIONS"
        mode: 0777
      become: "true"
      tags:
        - 305_place_INITIAL_INSTRUCTIONS