---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: 300 Clone required mediawiki version
      shell: "git clone --branch {{ mediawiki_version }} --depth 1 --single-branch https://github.com/wikimedia/mediawiki.git w/"
      args:
        chdir: "{{ system_root }}"
      tags:
        - 300_clone_mediawiki

    - name: 300 Install core extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "{{ system_root }}/w/"
      tags:
        - 300_clone_mediawiki
    
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/dserver/system_root/w
        owner: www-data
        group: dserver
        mode: 0777
      become: true
      tags:
        - 300_clone_mediawiki

    - name: 301 Place composer install script
      template:
        src: ../../ansible_templates/install_composer.sh.j2
        dest: "{{ system_root }}/w/install_composer.sh"
        mode: 0777
      tags:
        - 301_install_composer

    - name: 301 Install composer locally
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "cd {{ system_root_folder_in_container }}/w && ./install_composer.sh"
      tags:
        - 301_install_composer

    # [[IsOperationType::VendorPackageOperation]]
    - name: 302 Run composer inside container
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "cd {{ system_root_folder_in_container }}/w && php composer.phar install"
      tags:
        - 302_run_composer

    # [[IsOperationType::FileSystemOperation]]
    - name: 303 Place mediawiki install script
      template:
        src: ../../ansible_templates/install_mediawiki.sh.j2
        dest: "{{ system_root }}/w/install.sh"
        mode: 0777
      tags:
        - 303_install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: 303 Install mediawiki inside container
      shell: "docker exec {{ mediawikiDockerServiceName }} bash -c 'cd {{ system_root_folder_in_container }}/w && ./install.sh'"
      tags:
        - 303_install_mediawiki
    
    # [[IsOperationType::FileSystemOperation]]
    - name: 303 Place run_jobs_continuously.sh script
      template:
        src: ../../ansible_templates/run_jobs_continuously.sh.j2
        dest: "{{ system_root }}/w/run_jobs_continuously.sh"
        mode: 0777
      tags:
        - 303_install_mediawiki

    - name: 304 Add settings to LocalSettings.php
      lineinfile:
        path: "{{ system_root }}/w/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - $wgArticlePath = '/wiki/$1';
        - $wgServer = "http://{{ mediawikiDomainNameInHostFile }}:8080";
        - $wgFileExtensions[] = 'pdf';
        - $wgMainCacheType = CACHE_NONE;
        - $wgRateLimits['edit']['anon'] = [ 1, 1 ];
        - $wgEnableUploads = true;
        - $wgShowExceptionDetails = true;
      tags:
        - 304_adjust_localsettings

    # [[IsOperationType::VendorPackageOperation]]
    - name: 304 Change admin user password
      shell: docker exec {{ mediawikiDockerServiceName }} bash
               -c "cd {{ system_root_folder_in_container }}/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      tags:
        - 304_adjust_localsettings

    # [[IsOperationType::FileSystemOperation]]
    - name: 304 Set permissions on mediawiki root
      file:
        path: "{{ system_root }}/w/"
        owner: www-data
        recurse: yes
      become: true
      tags:
        - 304_adjust_localsettings

    - name: 304 execute_mediawiki_maintenance_runJobs
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "php w/maintenance/runJobs.php"
      tags:
        - 304_adjust_localsettings

    - name: 305 place INITIAL_INSTRUCTIONS
      template:
        src: ../../ansible_templates/INITIAL_INSTRUCTIONS.j2
        dest: "/home/dserver/INITIAL_INSTRUCTIONS"
        mode: 0777
      tags:
        - 305_place_INITIAL_INSTRUCTIONS