---

- hosts: localhost
  gather_facts: False
  tasks:
  
    - name: 320 Place MediaWiki extensions list
      template:
        src: ../../ansible_templates/{{ item }}.yml.j2
        dest: "{{ system_root }}/w/{{ item }}.yml"
        mode: 0777
      with_items:
        - mediawiki_extensions_by_composer
        - mediawiki_extensions_enable_only
        - mediawiki_extensions_from_repo
      tags:
        - 320_install_mediawiki_extensions

    - name: 320 Place MediaWiki extensions install script
      template:
        src: ../../ansible_templates/install_mediawiki_extensions.rb.j2
        dest: "{{ system_root }}/w/install_mediawiki_extensions.rb"
        mode: 0777
      tags:
        - 320_install_mediawiki_extensions
    
    - name: Change file ownership, group and permissions
      file:
        path: /home/dserver/system_root/w
        owner: www-data
        group: dserver
        mode: 0777
        recurse: yes
      become: true
      tags:
        - 320_install_mediawiki_extensions

    - name: 320 Install MediaWiki extensions
      shell: ruby install_mediawiki_extensions.rb
      args:
        chdir: "{{ system_root }}/w/"
      tags:
        - 320_install_mediawiki_extensions

    # [[IsOperationType::FileSystemOperation]]
    - name: 320 Set permissions on mediawiki root
      file:
        path: "{{ system_root }}/w/"
        owner: www-data
        recurse: yes
      become: "true"
      tags:
        - 320_install_mediawiki_extensions
