---

- hosts: localhost
  gather_facts: False
  tasks:

    # [[IsOperationType::RunDockerContainer]]
    - name: 330 execute_mediawiki_maintenance_runJobs
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "php w/maintenance/runJobs.php && php w/extensions/SemanticMediaWiki/maintenance/rebuildData.php"
      tags:
        - 330_execute_mediawiki_maintenance_runJobs
