version: "3.7"
services:
  mediawiki:
    container_name: mediawiki
    image: dataspects/php-apache:7.4.16_211010
    ports:
      - 80:80
    volumes:
      - ./mediawiki_root:/var/www/html/
    network_mode: host
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.5
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
    network_mode: host