---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy Elasticsearch config
      copy:
        src: ../../ansible_templates/control_scripts/elasticsearch
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      tags:
        - index_cookbook_entities

    - name: Copy indexing jobs
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - index_cookbook_entities.rb
      tags:
        - index_cookbook_entities

    - name: index_cookbook_entities
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - index_cookbook_entities.rb
      tags:
        - index_cookbook_entities
